### ISSUE TITLE
Could you provide other download links

### ISSUE THREAD

**Issue by coldmanck** [GriffinLiang/vrd-dsr#10]
I am interested in your work while I encountered difficulties when downloading files. The speed of downloading from Baidu Pan is merely ~10-20 kb/s, so it's impossible for me to get the both `faster_rcnn_1_20_7559.pth` and `epoch_4_checkpoint.pth.tar` files. Could you please upload to either [Google Drive](https://www.google.com/drive/), [Dropbox](https://www.dropbox.com) or [Box.com](https://www.box.com/home)?

**Comment by GriffinLiang** [comment]
I totally understand. However, it is difficult for me to upload the file
to Google Drive, Dropbox or Box.com. Right now, I suggest you train the
model from scratch. I will try to find some solutions to fix the problem.

2018-06-01 17:32 GMT+08:00 Meng-Jiun Chiou <notifications@github.com>:

**Comment by coldmanck** [comment]
Hi @GriffinLiang 

I am still trying to train your work, however I cannot even download this two files: `so_prior.pkl` & `vg.zip`. Can you provide the way to generate these files? As both are about ~25MB, can you split into multiple zip files and send me through the email so that I can upload them for you.

**Comment by GriffinLiang** [comment]
The download links on google drive are provided in the new README.md. Thanks for your suggestion.

**Comment by coldmanck** [comment]
Thank you for your help.
