### ISSUE TITLE
`None` elements in lists in train.pkl and test.pkl

### ISSUE THREAD

**Issue by GoodDeeds** [GriffinLiang/vrd-dsr#11]
In the list in train.pkl, 220 elements are `None`. In test.pkl, 45 elements are `None`.

The `None` elements are causing the training to fail as the program attempts to directly read the fields assuming a dictionary is present in every element of the list.

Could you please clarify the reason/significance of this, or if I am misunderstanding something?

Thank you.

**Comment by GriffinLiang** [comment]
We skip `None` elements while loading the data. https://github.com/GriffinLiang/vrd-dsr/blob/85d6b9b515d3b34dc86c9381f57c6e9349af9dbe/lib/data_layers/vrd_data_layer.py#L31

**Comment by GoodDeeds** [comment]
Thank you. I realized that it was not the training that was failing (as it should not, because None elements are skipped), but a preprocessing step of mine where I modify the paths in the pkl. Thank you very much for the clarification.

However, could you please clarify why some elements are None? Since the VRD dataset has 5000 images, and the train.pkl and test.pkl files have 4000 + 1000 elements each, are some images removed from the dataset?

**Comment by GriffinLiang** [comment]
Some images do not have any relationships. So I discarded them in the
training stage.

2018-06-07 13:51 GMT+08:00 Sukrut Rao <notifications@github.com>:
