### ISSUE TITLE
Steps to run code on a different dataset

### ISSUE THREAD

**Issue by GoodDeeds** [GriffinLiang/vrd-dsr#12]
I would like to run this code on a different dataset, and would like to know the steps to follow to do this correctly. So far, as I understand it, I need to do the following:

1. Create a new directory with the dataset name in ./data
2. Create train.pkl and test.pkl in the prescribed format for the training and test sets of the new dataset in this directory.
3. Create so_priors.pkl for the new dataset in this directory.

I use the command for training given in the README with the --dataset argument replaced with the directory name of the new dataset in ./data.

Could you please clarify what else would be needed?

A few queries in particular:

1. There is a PIXEL_MEANS variable in the code. Should this be set to the RGB mean values of the new dataset?
2. Should a new proposal.pkl be created? How should this be done?
3. How should the object detection network be trained? If trained separately, how is it to be integrated with relationship detection?
4. Are there any other changes needed?

Thank you.

**Comment by GriffinLiang** [comment]
1. There is a PIXEL_MEANS variable in the code. Should this be set to the RGB mean values of the new dataset?  
_No. You should use the default value._
2. Should a new proposal.pkl be created? How should this be done? 
_You have to train a object detector for your own dataset._
3. How should the object detection network be trained? If trained separately, how is it to be integrated with relationship detection? 
_Separately. Refer to https://github.com/GriffinLiang/faster-rcnn.pytorch/tree/773184a60635918e43b320eb1a0e8881779b90c8 to train object detection network and generate the proposal.pkl_

**Comment by GoodDeeds** [comment]
Thank you very much for the clarification.

**Comment by GoodDeeds** [comment]
Could you please clarify why the pixel means must not be changed? As I understand it, shouldn't it be the mean of the RGB channels of whatever training data is used? Thank you.

**Comment by GriffinLiang** [comment]
The pretrained VGG model uses the default PIXEL_MEANS.
