### ISSUE TITLE
where could i get the sg_dataset?

### ISSUE THREAD

**Issue by 978749951** [GriffinLiang/vrd-dsr#16]
I follow the Readme step by step, however, i still have troubles running the code. More specifically, I don't know sg_dataset means and where could i download it? Could you give me a hand? @GriffinLiang @GoodDeeds

**Comment by GriffinLiang** [comment]
Please refer to https://cs.stanford.edu/people/ranjaykrishna/vrd/.

**Comment by 978749951** [comment]
Thanks!
