### ISSUE TITLE
Data folder

### ISSUE THREAD

**Issue by medhini** [GriffinLiang/vrd-dsr#19]
Where do I get sg_dataset from? The dataset.zip folder in the link doesn't have train/test images. 
Shouldn't the folder structure also contain a VG sub-folder?

**Comment by GoodDeeds** [comment]
Please see #16

**Comment by medhini** [comment]
I'm sorry this doesn't answer my question. The data provided by you does not match the file structure you describe. What do you want me to download from the VRD homepage?

**Comment by GriffinLiang** [comment]
The link of image data is http://imagenet.stanford.edu/internal/jcjohns/scene_graphs/sg_dataset.zip. I will add it into README.

**Comment by medhini** [comment]
Thanks!

**Comment by emanuelazfernandes** [comment]
For anyone looking for the missing dataset (sg_dataset.zip), here is a Google Drive [link](https://drive.google.com/file/d/0Byvt-AfX75o1SVBTWFlPRGZGTXc/view?resourcekey=0-V3fW-908CLk30sxFVE9B-w).

From the other author's website: https://ranjaykrishna.com/index.html
