### ISSUE TITLE
something about the dataset

### ISSUE THREAD

**Issue by Destinyzs** [GriffinLiang/vrd-dsr#2]
I have questions about the dataset.
The data of vrd in the `train.pkl` and `test.pkl` is different from the ground truth which in the `sg_train_annotations.json` and `sg_test_annotations.json` ,and the amount of these objects and predicates are smaller than the ground truth too.
Have you modified the data?Is these bounding boxs&&object labels in the `test.pkl` predicated by fasterrcnn or taken directly from `sg_test_annotations.json`?

**Comment by GriffinLiang** [comment]
In the provided pkls, the coordinate of boxing box is zero-indexed with the order [x1, y1, x2, y2]. The duplicated objects and predicates are removed from the dataset.

**Comment by Destinyzs** [comment]
The data in `test.pkl` was got by faster-rcnn?

**Comment by GriffinLiang** [comment]
No. Is there anything wrong?

**Comment by Destinyzs** [comment]
So,the bounding box && object labels in `test.pkl` are just used to predict the predicates as supplementary information? Am i right?

**Comment by GriffinLiang** [comment]
Yes. For predicate detection, the bounding boxes and labels are given.

**Comment by Destinyzs** [comment]
All right,get it! Thanks!

**Comment by Destinyzs** [comment]
Hi,i come again...i have some question about the `args.proposal = '../data/vrd/proposal.pkl'`.
What‘s this proposal.pkl means?Is these  predicated by fasterrcnn ?

**Comment by GriffinLiang** [comment]
The file contains the detection results from the ECCV2016 paper (Visual Relationship Detection with Language Priors).

**Comment by Destinyzs** [comment]
ok,thanks.

Kongming Liang <notifications@github.com>于2018年4月12日 周四20:14写道：

**Comment by GriffinLiang** [comment]
Faster RCNN or some other object detection models.

2018-04-12 23:10 GMT+08:00 yangshao <notifications@github.com>:
