### ISSUE TITLE
Demo on video

### ISSUE THREAD

**Issue by sophia-wright-blue** [GriffinLiang/vrd-dsr#22]
Hello, 

Thank you for releasing this repo - it is awesome! Would it be possible to use the code to do a demo on a video? If yes, what would the steps be?

Thank you,

**Comment by GriffinLiang** [comment]
You can split the video into multiple frames and process each frame separately.

**Comment by sophia-wright-blue** [comment]
thank you for replying @GriffinLiang . i thought of that, but it won't take the temporal information in the video into account then, will give it a shot, thank you,
