### ISSUE TITLE
There seems no objective function for obj_score?

### ISSUE THREAD

**Issue by YuanEZhou** [GriffinLiang/vrd-dsr#25]
https://github.com/GriffinLiang/vrd-dsr/blob/9e1536ab2ce8eb41de66a6f1759b9264c783d6f5/lib/model.py#L28

**Comment by YuanEZhou** [comment]
![default](https://user-images.githubusercontent.com/17077323/48781465-09d84800-ed17-11e8-95bb-c93be3781d69.JPG)

**Comment by GriffinLiang** [comment]
Yes. For relationship detection, our proposed pipeline contains two stages. The first stage is object detection which provides the object confidence score. Therefore, the second stage does not need to predict the object score.

**Comment by YuanEZhou** [comment]
Ok. Thanks for your reply.
