### ISSUE TITLE
There is no function, called "res_detections" 

### ISSUE THREAD

**Issue by SeunghoHan** [GriffinLiang/vrd-dsr#26]
Hello,
Thank you for sharing this code.

While I tried to run the pre_demo in demo.py, I found an error, which is "cannot import name res_detections"

I already imported the Faster R-CNN following your instructions, and other functions in faster r-cnn are working well. 
There is only no res_detection function.. in faster-rcnn/lib/model/util/net_utils 

How can i solve it?

**Comment by GriffinLiang** [comment]
Sorry for the late reply. https://github.com/GriffinLiang/faster-rcnn.pytorch/blob/773184a60635918e43b320eb1a0e8881779b90c8/lib/model/utils/net_utils.py#L63

**Comment by SeunghoHan** [comment]
@GriffinLiang 
Thank you!

Actually, I tried to run these command to clone your repo
 $ git clone git@github.com:GriffinLiang/vrd-dsr.git
 $ git submodule update --recursive

But, it did not work for me. So, it tried to run again, changing some part like this.
 $ git clone --recursive git@github.com:GriffinLiang/vrd-dsr.git

**Comment by GriffinLiang** [comment]
Good. I will add this to README.
