### ISSUE TITLE
Question on gt.mat or gt.pkl

### ISSUE THREAD

**Issue by yangshao** [GriffinLiang/vrd-dsr#7]
It seems that all the information required has already been incorporated into the train.pkl/test.pkl, am i right?

**Comment by GriffinLiang** [comment]
Yes. These two files contain all the annotation information of VRD dataset.

**Comment by GriffinLiang** [comment]
The original eccv2016 paper suggests to use recall due to the
incompleteness of annotations.

2018-04-19 15:19 GMT+08:00 yangshao <notifications@github.com>:
