### ISSUE TITLE
Question about so_prior.pkl

### ISSUE THREAD

**Issue by xuewenyuan** [GriffinLiang/vrd-dsr#9]
1. When I use _word2vec_ to map the obeject category into a feature embedding vector, how should I prepare the sentences used for _word2vec_ model ? (like 'person near building'?)

2. The tensor of _so_prior.pkl_ has a shape of (100, 100, 70), which represents 100 obeject categories and 70 predicates. Once I have a _word2vec_ model that can map a obeject category into a feature embedding vector, how can I create _so_prior.pkl_? Specifically, how can I concatenate the embedding vectors of _subject_ and _object_ for a special predicate?

Thank you!

**Comment by xuewenyuan** [comment]
@GriffinLiang thank you for your  reply! But I'm still confused about how to calculate _so_prior.pkl_ on my dataset. If I understand correctly, _so_prior.pkl_ stores the items <a href="https://www.codecogs.com/eqnedit.php?latex=\Delta(r,r^{'})" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\Delta(r,r^{'})" title="\Delta(r,r^{'})" /></a> that is mentioned in your paper. Could you please share with me more?

**Comment by xuewenyuan** [comment]
@GriffinLiang thank you for your  reply! But I'm still confused about how to calculate _so_prior.pkl_ on my dataset. If I understand correctly, _so_prior.pkl_ stores the item <a href="https://www.codecogs.com/eqnedit.php?latex=\Delta(r,r^{'})" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\Delta(r,r^{'})" title="\Delta(r,r^{'})" /></a> that is mentioned in your paper. Could you please share with me more?

**Comment by GriffinLiang** [comment]
so_prior.pkl contains the conditional probability given subject and object. For example, if we want to calculate p(ride|person, horse), we should find all the relationships describing person and horse and the exact relationships of person-ride-horse. We use N and M to denote the number of the above two relationships, and p(ride|person, horse) can be simply acquired as N/M.

**Comment by GoodDeeds** [comment]
@GriffinLiang Is `so_prior.pkl` stored in (subject, object, predicate) format? As the shape is (100,100,70), I wanted to clarify against the other possibility - (object, subject, predicate). Thank you.

**Comment by GriffinLiang** [comment]
You are right, The order is (subject, object, predicate) .

2018-05-31 15:02 GMT+08:00 Sukrut Rao <notifications@github.com>:

**Comment by GoodDeeds** [comment]
Thank you for the clarification.

**Comment by lileilai** [comment]
@xuewenyuan 请问你有成功复现这篇文章吗？有一些问题想请教您，期望您能解答一下，谢谢。

**Comment by xuewenyuan** [comment]
@lileilai yeah, what's your question?

**Comment by xuewenyuan** [comment]
> > @lileilai yeah, what's your question?
> 
> 你好，可以解释一下损失函数吗？按照论文里的公式，没有理解代码．

Sorry for replying you so late. Recently, I wrote a [note](https://xuewenyuan.github.io/posts/2018/12/blog-post-8/) for this paper. If you still have questions after reading, please send me an email.

**Comment by lileilai** [comment]
不好意思  没有再follow这篇文章了，


关于损失函数可以看它的代码实现，由于分类类别太多，所以主要是基于hinge loss的这种形式





目的是让正例（标注的关系）的得分更好，负例（负采样的关系）变差。其中的阀值  作者设计中加入了先验知识条件概率




我大概也就知道这么多  希望能帮到你
 
 
------------------ Original ------------------
